[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#555555"
blue = "#1E6FCC"
cyan = "#158C86"
green = "#216609"
magenta = "#5C21A5"
red = "#CC3E28"
white = "#AAAAAA"
yellow = "#B58900"

[colors.normal]
black = "#000000"
blue = "#1E6FCC"
cyan = "#158C86"
green = "#216609"
magenta = "#5C21A5"
red = "#CC3E28"
white = "#AAAAAA"
yellow = "#B58900"

[colors.primary]
background = "#F2EEDE"
foreground = "#000000"

[font]
size = 10.0

[font.bold]
family = "Cascadia Code"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Cascadia Code"
style = "Italic"

[font.normal]
family = "Cascadia Code"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 0

[window]
opacity = 1.0
