# Don't print a new line at the start of the prompt
# add_newline = false

[character]      # The name of the module we are configuring is "character"
success_symbol = "[𝝿](bold green)"     # The "symbol" segment is being set to "➜"

[directory]
truncation_length = 4
truncate_to_repo = false

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[custom.nomad_env]
when = "test -f .env && grep -q '^NOMAD_ENV=' .env"
command = "source .env && echo $NOMAD_ENV"
style = "bold green"
format = "[\\(nomad $output\\)]($style)"
