[theme]
background = "black"
primary = "light white"
secondary = "green"
title = "white"
playing = "yellow"
playing_bg = "black"
highlight = "white"
highlight_bg = "#004a87"
error = "light white"
error_bg = "red"
statusbar = "white"
statusbar_progress = "#007957"
statusbar_bg = "#004a87"
cmdline = "light white"
cmdline_bg = "black"
